[심기성] RacingGame step1코드리뷰 부탁드립니다.
SimKiSeong/java-study-racingGame pull request #2
Opened 2019-01-09 08:48 UTC by SimKiSeong

[심기성] RacingGame step1코드리뷰 부탁드립니다.

2019-01-09 12:47 UTC, Bellroute reviewed
객체지향 특성을 잘 살려서 코드를 구현하면 좋을 것 같습니다. input을 담당하는 객체로부터 입력값을 받고, game을 돌리는 객체에 그 값을 전달한 뒤, 입력받은 자동차 대수만큼 자동차라는 객체를 생성해서 이동시키고, 그 결과를 output담당 객체에서 출력을 하는 방식으로요.

2019-01-09 12:47 UTC, Bellroute commented on src/main/java/RacingGame.java
> +    private void inputCarNumber() {
하나의 클래스는 하나의 역할을 하도록 분리하는 것이 좋습니다. 입력을 받는 메소드가 담긴 클래스 따로, 게임을 진행시키는 컨트롤러 클래스 따로, 출력을 담당하는 클래스 따로 구분해서요.

2019-01-09 12:47 UTC, Bellroute commented on src/main/java/RacingGame.java
> +    private void inputTryNumber() {
입력 받는 메소드

2019-01-09 12:47 UTC, Bellroute commented on src/main/java/RacingGame.java
> +    public void printResult() {
출력하는 메소드

2019-01-09 15:23 UTC, hyukjin-lee requested changes
객체지향, MVC 패턴 공부해서 다시 코드를 역할과 책임에 따라 분리시켜 보세요

2019-01-09 15:23 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +    public void playRaciongGame() {
오타.

2019-01-09 15:23 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +public class RacingGame<puiblic> {
<puiblic> 스펠링도 틀렸고 왜 쓴건지 궁금합니다

2019-01-09 15:23 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +    public int goOrStop(int randomNumber) {
```suggestion
    public boolean isMove(int randomNumber) {}
```

제가 보기엔 boolean 함수같습니다. boolean 함수 컨벤션은 is~입니다. 

true false를 리턴 받는 함수를 편의에 따라서 1, 0 으로 변환하는 작업은 지양해주세요

2019-01-09 15:23 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +    private void inputCarNumber() {
디자인패턴중에 MVC pattern을 공부하고 진행해보세요

2019-01-09 15:23 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +        String positionString = "";
변수명에는 자료형을 이름으로 붙이지 않습니다

2019-01-09 15:23 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +            positionString = positionString + "-";
하드코딩을 하지 말자는 스터디 원칙이 있습니다.

2019-01-09 15:23 UTC, hyukjin-lee commented on src/main/java/RacingGame.java
> +    }
RacingGame이 하는 일이 너무 많네요. 다시 유지보수, 확장성을 고려하면서 설계를 해보시길 바랍니다.

2019-01-09 15:23 UTC, hyukjin-lee commented on src/test/java/RacingGameTest.java
> +        assertEquals(true, checkNumber(racingGame.getRandomNumber(), 10));
랜덤값이 특정 범위 안에 있는지 확인만 하는거면 그다지 의미없는 테스트이지 않을까요? 랜덤 테스트하려고 엄청난 고민을 해서 참신한 결과가 나온 것 같은데 도전은 매우 좋은 것 같습니다. 하지만 랜덤, DB 같이 계속 변화하는 것들에 대한 테스트는 애초에 유의미한 테스트가 불가능한 것들이므로 이러한 것들로부터 영향을 많이 받지 않고 독립적으로 테스트를 할 수 있게 설계를 개선시켜야합니다. 프로덕션 코드 < 테스트 코드가 우선순위라고 생각하세요. 테스트가 이상하고 불가능하면 프로덕션 코드 설계를 바꿔야합니다. 지금 여기서 반영하라는 피드백은 아니구요. 앞으로 그냥 기억하시라는 말~

2019-01-09 15:23 UTC, hyukjin-lee commented on src/test/java/RacingGameTest.java
> +    }
전체적으로 이제 대충 테스트 감 좀 잡으신거 같네요 ㅎㅎ 좋습니다

2019-01-10 03:46 UTC, wijehyeon commented on src/main/java/RacingGame.java
> +        if(nowResult>=4){
4라는 특정 값이 무엇을 의미하는지 확인할 수 있게 상수로 정해두는것은 어떨까요

2019-01-10 03:52 UTC, wijehyeon commented
main폴더 안에 있는 클래스들을
model package, view package, controller package로 나눠서 구분해두면 좋을 것 같습니다

2019-01-10 06:39 UTC, esp2ar0 commented on src/main/java/RacingGameInput.java
> +public class RacingGameInput {
클래스 명이 전체적으로 부적절해보입니다. 모든 클래스 이름이 RacingGame으로 시작하고 있기 때문일까요?
project 이름에 racingGame이 포함된 만큼 해당 단어는 생략 가능해 보입니다.
참고로 힌트 부분에
- UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.
라고 나와있습니다.

2019-01-10 06:40 UTC, Bellroute commented on src/main/java/RacingGameTools.java
> +    public int tryNumber;
접근 제한을 private으로 돌리고 set, get 메소드를 활용하면 어떨까요

2019-01-10 06:40 UTC, Bellroute commented on src/main/java/RacingGameInput.java
> +    public RacingGameTools setting() {
Input을 담당하는 클래스에서 세팅을 하는 일도 하고 있습니다.

2019-01-10 06:40 UTC, Bellroute commented on src/main/java/RacingGame.java
> +    private RacingGameOutput racingGameOutput = new RacingGameOutput();
메인 메소드를 갖는 어플리케이션 클래스를 따로 만들어 메인에서 다른 클래스들이 실행되게 하는 것이 좋을 것 같습니다.

2019-01-10 06:46 UTC, esp2ar0 commented on src/main/java/RacingGameInput.java
> +    public RacingGameTools setting() {
setting() 메소드를 쓰는 대신에
입력 받는 메소드에서 각각 필요한 정보들을 인자로 받으면 되지 않을까요?

2019-01-10 06:47 UTC, esp2ar0 commented on src/main/java/RacingGameTools.java
> +    public int tryNumber;
클래스 명과 클래스가 하는 일이 명확해 보이지 않습니다

2019-01-10 06:48 UTC, esp2ar0 commented on src/main/java/RacingGameOutput.java
> +                System.out.print('-');
'-'를 출력하는 것은 어떤 의미인지 파악하기 힘듭니다.
이런 것을 하드 코딩이라고 합니다
상수로 선언해서 명확하게 나타내면 어떨까요?

2019-01-10 06:49 UTC, esp2ar0 commented on src/main/java/RacingGame.java
> +    private RacingGameOutput racingGameOutput = new RacingGameOutput();
Input과 Output 클래스의 객체를 생성해 주고 있습니다.
View 클래스들의 메소드는 1회성 메소드들이 많기 때문에, 객체를 생성해 주기 보다는 클래스 내부 메소드들을 static으로 선언해 간단하게 사용해 주는 것이 더 좋아 보입니다.
라이브러리의 하나인 Math 클래스처럼 말이죠.

2019-01-10 06:52 UTC, esp2ar0 commented on src/main/java/RacingGame.java
> +        if(nowResult>=4){
> 4라는 특정 값이 무엇을 의미하는지 확인할 수 있게 상수로 정해두는것은 어떨까요

return의 1과 0도 마찬가지입니다.
이런것을 하드코딩이라고 합니다.

2019-01-10 06:55 UTC, esp2ar0 commented on src/main/java/RacingGame.java
> +    private int randomResult(){
메소드 네이밍 컨벤션에 어긋나 보입니다

2019-01-10 06:55 UTC, esp2ar0 commented on src/main/java/RacingGame.java
> +        int nowResult = random.nextInt();
이 경우 nowResult가 갖게 되는 값의 범위가 어떻게 되나요?

2019-01-10 06:57 UTC, esp2ar0 commented
전체적으로 열심히 한 흔적이 보이며 처음인데도 잘 구현 하셨네요.
MVC 패턴의 이해와 네이밍이 약간 아쉬웠습니다.

2019-01-11 08:35 UTC, esp2ar0 commented on src/main/java/com/econo/racingGame/controller/RacingGameController.java
> +    final static int MOVEBOUNDARY = 4;
접근제어자 붙여주세요

2019-01-11 08:42 UTC, esp2ar0 commented on src/main/java/com/econo/racingGame/controller/RacingGameController.java
> +    public GameDB makeResult(GameDB gameDB){
모델의 상태를 가지고 와서 모델의 상태를 조작해주는 메소드 맞나요?
그렇다면 모델 내부에 두는 것이 더 효율적이지 않을까요?

2019-01-11 08:42 UTC, esp2ar0 commented on src/main/java/com/econo/racingGame/controller/RacingGameController.java
> +    public int individualResult(GameDB gameDB){
메소드 네이밍 컨벤션에 어긋납니다

2019-01-11 08:44 UTC, esp2ar0 commented on src/main/java/com/econo/racingGame/controller/RacingGameController.java
> +        for(int i = 0; i< gameDB.tryNumber; i++){
i와 <부분만 띄어쓰기를 쓰지 않았네요. 이런 사소한 부분도 신경써야합니다.
푸쉬 전에 자동 라인 정렬 기능을 꼭 사용합시다

2019-01-11 08:47 UTC, esp2ar0 commented on src/main/java/com/econo/racingGame/model/GameDB.java
> +public class GameDB {
이 클래스는 자동차들의 위치, 시도 횟수를 가지고 있습니다.
GameDB라는 이름은 명확하지 않아 보입니다.
모델에 DB라는 이름.. 잘 모르겠으나 개인적으로는 부적절해보이네요 @hyukjin-lee 의견좀~~ㅎ

2019-01-11 08:48 UTC, esp2ar0 commented on src/main/java/com/econo/racingGame/model/GameDB.java
> +    public int[] carPositions;
객체 내부의 변수들을 public으로 선언해주면 외부에서 접근할 수 있어 예상치 못한 에러를 유발합니다.

2019-01-11 08:49 UTC, esp2ar0 commented on src/test/java/RacingGameControllerTest.java
> +
불필요한 라인 정리!

2019-01-12 14:44 UTC, Bellroute commented on src/main/java/com/econo/racingGame/controller/RacingGameController.java
> +        int nowResult = random.nextInt(10);
랜덤 값을 추출하는 기능은 경우에 따라 다시 사용될 수 있는 기능이기 때문에 코드 재사용성을 고려해 Util이라는 클래스에 담고, static으로 구현을 해 객체를 생성하지 않고도 사용할 수 있도록 하는 방법도 아이디어가 될 수 있을 것 같습니다

2019-01-13 12:02 UTC, hyukjin-lee requested changes
앞으로 미션 수행하면서 제약사항이 하나 둘 씩 늘어날겁니다. 유연하게 대처할 수 있도록 최대한 설계를 잘 해보세요. 빠른 시간안에 정말 열심히 해주는거 같아서 보기 좋습니다. 화이팅

2019-01-13 12:02 UTC, hyukjin-lee commented on src/main/java/com/econo/racingGame/controller/RacingGameController.java
> +public class RacingGameController {
MVC 패턴이라는 걸 공부해서 인지하셨으면, 그걸 책임과 역할의 분리 측면에서만 접근하시고 실제 이 코드에 Controller View Model을 학문에 나온 것을 100퍼센트 활용해서 구체적으로 적용하려하지는 마세요. 저희는 MVC 패턴을 구현하는게 아니라 객체지향 공부가 목적이라서 책임과 역할의 분리 측면에서만 활용해야 객체지향에 좀 더 집중할 수 있을 것 같습니다. 따라서 Controller라는 이름은 빼셔도 무방할 것 같습니다. RacingGame이라는 개념이 가져야하는 책임과, 해야하는 역할을 생각해서 코드를 짜보세요

2019-01-13 12:02 UTC, hyukjin-lee commented on src/main/java/com/econo/racingGame/model/GameDB.java
> +public class GameDB {
데이터베이스가 아닙니다. MVC 열심히 공부한건 정말 좋습니다. 하지만 이 코드는 지금 객체지향 공부를 하기 위해 하고 있는 것이므로, 위에 말씀드렸다시피 책임과 역할에 따라 객체들을 나누는 것에 집중하는게 좋을 것 같습니다. 제가 보기엔 Model 레이어에 Car라는 개념이 GameDB를 대신할 수 있을 것 같네요

2019-01-13 12:02 UTC, hyukjin-lee commented on src/main/java/com/econo/racingGame/model/GameDB.java
> +public class GameDB {
Car라는 개념의 책임과 역할에 대해 생각하면서 어떤 필드를 가지고 있어야 하는지, 어떤 기능(함수)들을 가지고 있어야 하는지 생각해보시길 바랍니다

2019-01-13 12:02 UTC, hyukjin-lee commented on src/main/java/com/econo/racingGame/view/InputVIew.java
> +    public static int carNumber() {
static으로 구현 Good 👍

2019-01-13 12:02 UTC, hyukjin-lee commented on src/main/java/com/econo/racingGame/view/ResultView.java
> +    private static final char BAR = '-';
하드코딩 최소화 굿 👍

2019-01-13 12:02 UTC, hyukjin-lee commented on src/main/java/com/econo/racingGame/view/InputVIew.java
> +        return carNumber;
return scanner.nextInt(); 로 코드라인 줄여도 좋을 것 같네요 (아래도)

2019-01-13 12:02 UTC, hyukjin-lee commented on src/main/java/com/econo/racingGame/view/InputVIew.java
> +        Scanner scanner = new Scanner(System.in);
scanner를 중복으로 사용하고 있으니 밖으로 꺼내서 사용해도 될 것 같습니다. (static으로 구현하는게 더 어울리는지 알아보고 적용해보세요)

2019-01-13 12:02 UTC, hyukjin-lee commented on src/test/java/RacingGameControllerTest.java
> +public class RacingGameControllerTest {
단위테스트는 클래스별로 할 수 있는건 다 해주세요. 지금은 RacingGameController 테스트 밖에 없어서 아쉽습니다.

2019-01-13 13:15 UTC, wijehyeon commented on src/main/java/RacingGameTools.java
> +
이 클래스가 경주중인 "자동차"들의 위치도 가지고있고, 그 "게임"의 시도횟수도 가지고있는데
자동차의 각 위치라는 속성은 자동차 객체가, 시도횟수라는 속성은 게임을 다루는 클래스가 가지고 있도록 설계하는것도 좋을 것 같습니다.

2019-01-13 13:15 UTC, wijehyeon commented on src/main/java/com/econo/racingGame/controller/RacingGameController.java
> +    final static int MOVEBOUNDARY = 4;
상수명 작성할때 대문자로만 작성하면 camelcase보다 가독성이 줄어들어서
MOVE_BOUNDARY라고 해도 좋다고 배웠습니다.

2019-01-13 13:15 UTC, wijehyeon commented on src/main/java/com/econo/racingGame/controller/RacingGameController.java
> +    private int goStop(){
고스톱이 생각나는 함수이름입니다
forwardOrStop같은 네이밍도 가능하겠네요

2019-01-13 13:15 UTC, wijehyeon commented on src/main/java/com/econo/racingGame/model/GameDB.java
> +
game의 정보를 담고있는 GameDB를 model로 선정했는데
carPositions는 자동차의 나아간 정도, 위치를 나타내는 속성입니다. 게임정보에 대한 속성일 수 있지만 그전에
자동차의 속성이기도 해서 자동차라는 model도 설계과정에 넣었으면 물론 클래스의 수는 늘어나긴 하겠지만 객체단위로 잘 쪼개진 느낌이 나지 않을까요?

2019-01-13 13:15 UTC, wijehyeon commented on src/main/java/com/econo/racingGame/model/GameDB.java
> +
추가로 model에서 정보를 가져오기 위해 
DTO(Data Transfer Object)도 활용하는 방향으로 다음에는 설계하는것도 공부에 도움될 것 같습니다

2019-01-13 13:15 UTC, wijehyeon commented on src/main/java/com/econo/racingGame/view/InputVIew.java
> +public class InputVIew {
VIew의 I가 대문자네요 ㅎㅎ 작은실수

2019-01-15 07:37 UTC, esp2ar0 commented on src/main/java/com/econo/racingGame/view/InputVIew.java
> +public class InputVIew {
> VIew의 I가 대문자네요 ㅎㅎ 작은실수

예리하다....ㅋㅋㅋㅋㅋㅋ

2019-01-19 13:27 UTC, wijehyeon commented
매번 PR마다 리뷰반영 피드백 설계가 계속 발전하네요 .. ㄷㄷ
static으로 쓰일 필요 없는 함수가 있다면 static 빼주는것만 해주면 좋을것같습니다.
수고하셨어요!

2019-01-19 13:29 UTC, wijehyeon commented on src/main/java/com/econo/racingGame/view/InputView.java
> +
InputView클래스의 함수들이 static으로 쓰여야하나요?

2019-01-19 13:38 UTC, wijehyeon commented on src/test/java/RacingGameTest.java
> +        if(tryNumber>=distance){
boolean 반환 함수의 네이밍 컨벤션은 is~입니다
근데 이 함수는 is~로 어떤 네이밍으로 해야 좋을지..

2019-01-21 13:19 UTC, merged

2019-01-21 13:20 UTC, hyukjin-lee commented on src/test/java/RacingGameTest.java
> +        if(cars.length==carNumber){
피드백 반영 좋습니다 제발 2단계 진행해주세요...

2019-01-21 13:21 UTC, wijehyeon commented on src/test/java/RacingGameTest.java
> +        if(cars.length==carNumber){
제발 2단계 진행해주세요

2019-01-21 13:51 UTC, hyukjin-lee reviewed
https://github.com/JNU-econovation/java-study-racingGame/pull/13/files
https://github.com/JNU-econovation/java-study-racingGame/pull/12/files
https://github.com/JNU-econovation/java-study-racingGame/pull/10/files
https://github.com/JNU-econovation/java-study-racingGame/pull/9/files
https://github.com/JNU-econovation/java-study-racingGame/pull/8/files
https://github.com/JNU-econovation/java-study-racingGame/pull/6/files

리팩토링하느라 고생많으셨습니다. 마지막으로 다른사람 코드들 천천히 책 읽듯이 읽어보시고 배울점이 있으면 자신의 코드에 반영시켜보고 1단계 마무리 하십쇼~ 짱짱맨

2019-01-21 13:51 UTC, hyukjin-lee commented on src/test/java/RacingGameTest.java
> +        if(cars.length==carNumber){
라인 정렬좀 누르고 제출해주세요

2019-01-21 13:51 UTC, hyukjin-lee commented on src/test/java/RacingGameTest.java
> +}
테스트도 클래스에 맞춰서 진행해야하는데 한 테스트파일에 때려박은걸 분리시키는게 좋습니다